# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: cykhash

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11', pypy-3.8, pypy-3.9]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
           # macos has issues with numpy for some versions
           - python-version: pypy-3.6
             platform: macos-latest             
           - python-version: pypy-3.7
             platform: macos-latest
        
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip    
        pip install .
        pip install pytest
        pip install numpy
        pip install cython
    - name: Test with pytest
      run: |
        (cd tests/unit_tests && pytest)
        
    - name: Run doctests repository
      run: |
        pytest --ignore=tests --doctest-glob=*.md --doctest-glob=*.pyx --doctest-glob=*.pxi -vv  --doctest-continue-on-failure
        
    - name: Run doctests installation
      run: |
        (cd tests && python run_installed_doctests.py)
